### ISSUE TITLE
Every release is created with all the previous commits from previous releases as well

### ISSUE THREAD

**Issue by efraimbart** [rymndhng/release-on-push-action#64] opened 2021-10-29 07:26 UTC
The only thing I could think of that is out of the ordinary is the first release is a pre-release that's been made manually.

Any idea why this would be happening?

**Comment by rymndhng** [comment] 2021-11-02 07:23
The action is currently implemented by using the latest release, which must be a non-prerelease and non-draft release. 

See https://docs.github.com/en/rest/reference/repos#get-the-latest-release

**Comment by efraimbart** [comment] 2021-11-03 21:50
Only the first release is a pre-release, yet this still happens even though there have been multiple subsequent proper releases

**Comment by rymndhng** [comment] 2021-11-04 05:00
At a high level, the logic for extracting commits paginates via the commits API from the current SHA and stops when it encounters the SHA for the `latest` release.

I tried to reproduce this in this repository and I can't seem to reproduce the issue.  See https://github.com/release-on-push-action/test-with-prerelease/releases

1. The first release is a manually created pre-release. 
2. The second release includes the commits *before* pre-release since API selects the latest release that is non-draft & non-prerelease.
3. The third release only includes commits *after* the second release because we're no longer using pre-releases.

Would you be able to show me which repository this is happening (if it's public). If not, perhaps you can share with me the logs from the the build.

**Comment by efraimbart** [comment] 2021-11-04 14:13
It could be because I edited the second release's release notes to no longer include the pre-release notes. Perhaps that causes a chain of events?

Repo: https://github.com/efraimbart/OpenInWSA

**Comment by rymndhng** [comment] 2021-11-09 04:57
Looking at the history, I suspect what happened is that somehow the release `v0.1.0` triggered on a commit *before* merging to `main`. When the Github Action for `v0.2.0` kicked off, the paginator only paginates through commits in it's history (it does not include commits from merge commits, which is why it probably jumped from `164164b` to `f0aca4e` and skipped `493d888`.

```
❯ git log --graph --oneline
* 3511d82 (tag: v0.4.0) Smartend up the adb path finding and validation a whole bunch
* 64bfb57 Refactored browser stuff
* eb5eb4a Don't show console unless input/output is needed
* 4e25539 Missed a word
* a5d7ba5 (tag: v0.3.0) Refactored WSA and AdbClient
*   164164b (tag: v0.2.0) Merge branch 'main' of https://github.com/efraimbart/OpenInWSA
|\
| * 493d888 (tag: v0.1.0) Update action to properly upload exe
| * 8c5afc9 Another attempt to fix version in github actions
| * b515fb7 Attempt fix for build version in github action
| * fd2f21a Updated action to allow pre-release
* | f0aca4e Refactored to clean things up and break things out a bit more
* | 07a32b6 Added the ability to deregister as a browser
* | c29168e If default browser has since been uninstalled request user update their default
* | 2b3bd10 Updated Open In WSA naming convention for better end user experience
|/
* 9e1fe43 Github action to auto-build exes
* 7527f42 Refactor fallback to default browser to check the parent process rather than query string
* 4ee0613 Remove .idea from repo
* ea7e5ca Remove default browser loop
* def5ccf Update build config
* 7609e78 (tag: v0.0.1) Initial commit
```

**Comment by efraimbart** [comment] 2021-11-09 15:29
Does it make sense that this would leave it in a broken state for subsequent releases as well or is the same issue repeating itself for those releases?

Perhaps something related to this, I've started to avoid merging the pull requests from within github because it doesn't allow fast forward merges.

**Comment by rymndhng** [comment] 2021-11-15 02:22
I think it should only be broken for one release -- unless the Github Action is always triggering off a non-mainline commit. I haven't see this in your project's history other than on tag v0.1.0.

> Perhaps something related to this, I've started to avoid merging the pull requests from within github because it doesn't allow fast forward merges.

Have you considered enabling the "Rebase" merge strategy? I think it's meant to achieve something similar to what you want.

**Comment by efraimbart** [comment] 2021-11-15 02:29
So this release notes issue happened with most of the releases in this project, what does this tell us?

**Comment by rymndhng** [comment] 2021-11-15 06:05
Indeed you are correct! I didn't notice that you scrubbed every release to remove the extra commits.

---
Here's what I noticed looking at the API side -- in the API call to fetch the latest release for your project, it seems the `target_commitish` is set to the branch `main` instead of a `sha`. I would expect it to be a `sha` if the release is created using this plugin.

```
❯ curl -H"Authorization: Bearer ${GITHUB_TOKEN}" -H"Accept: application/vnd.github.v3+json" https://api.github.com/repos/efraimbart/OpenInWSA/releases | jq '.[] | [.tag_name, .target_commitish]' -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37973  100 37973    0     0  81292      0 --:--:-- --:--:-- --:--:-- 83640
["v0.7.1","main"]
["v0.7.0","main"]
["v0.6.0","main"]
["v0.5.0","main"]
["v0.4.0","3511d82c7777dd4a1ce16bc9b795f9a4ae667e23"]
["v0.3.0","main"]
["v0.2.0","main"]
["v0.1.0","main"]
["v0.0.1","main"]
```

Compare this to the output on the release-on-push-action project itself.

```
❯ curl -H"Authorization: Bearer ${GITHUB_TOKEN}" -H"Accept: application/vnd.github.v3+json" https://api.github.com/repos/rymndhng/release-on-push-action/releases | jq '.[] | [.tag_name, .target_commitish]' -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69376  100 69376    0     0   109k      0 --:--:-- --:--:-- --:--:--  113k
["v0.23.0","2af2de966ddc26cf72cb55dfdd2c800b8e1da22f"]
["v0.22.0","4949747a8b351fa1587cedc0fbc22719a66b2271"]
["v0.21.1","b064110f3666de892b28eb417abde47694c51480"]
["v0.21.0","ebcb13adb918935afc47b2092e6de5f5d31a08f1"]
["v0.20.0","37495bfef4e97937ef7f25b2ba9fddb63489dc3b"]
["v0.19.0","f49165bfc26213c8b163812f415aa71a47a8c020"]
["v0.18.0","987a8483eb94aacb05f7c7ac69527ec6f9b666ce"]
["v0.17.0","8c4b0acaac362d6a23bc9c10271953f96d7ced05"]
["v0.16.0","9bf66ab47d66543c6ebacc0ad9ef4312e3e3e33f"]
["v0.15.0","fa0af843b9cbeda2375120a52c5c364a4b824ab1"]
["v0.14.0","df2f7a3b2c3370b9847c520f6aac857efa00794e"]
["v0.13.3","5ec95a46c177e20f491b356f05e4d4ae1467f394"]
["v0.13.2","ca0a4e528903ca07ac4f1cbbefbc6354fe33cf19"]
["v0.13.1","6a87ac2f2dee3c014bd93421f453b1bd9eadb5b4"]
["v0.12.1","1eaa84f6eab9694bde473570ab13dcb245ecd00c"]
["v0.12.0","b208163d04317d600d7366d647707f00160199dc"]
["v0.11.0","f962ca17c370e87226a9ee5a1c658cb2bb52d74c"]
["v0.10.0","167c690247d0933acde636d72352bcd67e33724b"]
["v0.9.3","85f8a44fefdbad64b57f2ae53e38b36255f0c3a8"]
["v0.9.2","afc93804032d93d8a32db4578c10309257e57d66"]
["v0.9.1","2dd68fa6b3adc5f4d536fd4139a92036f51d7648"]
["v0.9.0","f42a728f2666d873780c5e01c49dc629e8e7f32a"]
["v0.8.0","23d379c43a97727ab7effe55701aaa59cb9272d5"]
["v0.7.0","8b815a55d464fc5021b58427fff2cc0d37d2c1e2"]
["0.6.1","fd41208d9aad4fdd233e9f6a098ae62e84a569f4"]
["0.6.0","afb6eece7158d0ee0513f48cd4fcf27342c4254e"]
["0.5.0","bd5a05adda18106b2114581ac2df141c68ba9b90"]
["0.4.0","3198e057fba0da8eb300851e76759a74aea86e15"]
["0.3.0","c3db7b6995dec725770c96e4b34b3f644fe1e7c0"]
["0.2.0","a23a6d810d34695f2837a422acfedb937a0461e6"]
```

---
From inspecting your project, I notice you're using another Action to update the releases. I looked at that project's code and I have a theory that the other project is updating the `Release` resource incorrectly. In the linked code, I think this will always be an empty string, and will default to setting `target_commitish` to the name of the branch. This will always be empty beause the input name `commit` is not provided by the user. See https://github.com/ncipollo/release-action/blob/95aae1ba969a2d54a67dfe3e237980192d2d91b7/src/Inputs.ts#L86-L88

To test this theory, I tried to reproduce this behaviour in an API call to update an existing release with an empty commitish, like so:

```
❯ cat payload.json
{ "target_commitish": "" }

❯ curl -X PATCH -H"Authorization: Bearer ${GITHUB_TOKEN}" -H"Accept: application/vnd.github.v3+json" https://api.github.com/repos/release-on-push-action/bug-test/releases/49762240 --data-binary @payload.json

# make a request to show target_commitish
❯ curl -H"Authorization: Bearer ${GITHUB_TOKEN}" -H"Accept: application/vnd.github.v3+json" https://api.github.com/repos/release-on-push-action/bug-test/releases | jq '.[] | [.tag_name, .target_commitish]' -c
["4.49.0","master"]
["bb0.1.0","53e0f36210cd8991593adbe037377e2559270029"]
```

Voila! Now my `target_commitish` has changed to `master`.

---

This is a new interaction to me that I hadn't accounted for. The commit log generator made an assumption that the `target_commitish` is a `sha` since the releases are created by this action. 

This is definitely a bug, and I think I can avoid this by resolving the `tag` -> `commit`, rather than relying on the `target_commitish`.

**Comment by rymndhng** [comment] 2021-11-15 06:40
@efraimbart a new version is out which should resolve this issue. Let me know how it goes!

**Comment by efraimbart** [comment] 2021-11-15 21:06
Thanks a bunch! I will update the action to point to the latest version, but not sure when the next release will be, so let me know if you'd like me to create a release just to test this.

**Comment by rymndhng** [comment] 2021-11-16 07:05
I tried out the fix in a test repo https://github.com/release-on-push-action/bug-test with branch as a target_commitish and it seems to be working!

When you get a chance to release though and run into this problem again,re-open this issue or create a new one. 

Cheers!

**Closed by rymndhng** 2021-11-16 07:05 UTC
